# Generated by Django 4.2.2 on 2024-06-16 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="введите дату создания токена",
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Token"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="токен для восстановления пароля",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="токен для восстановления пароля",
                    ),
                ),
            ],
        ),
    ]
