# Generated by Django 4.2.2 on 2024-06-17 08:30

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_usertoken"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
