# Generated by Django 4.2.2 on 2024-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_is_admin_user_is_content_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Выберите аватар",
                null=True,
                upload_to="users/avatars",
                verbose_name="аватар",
            ),
        ),
    ]
