# Generated by Django 4.2.2 on 2024-06-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False, verbose_name="Забанен"),
        ),
    ]
