# Generated by Django 4.2.2 on 2024-06-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                help_text="slug",
                max_length=250,
                null=True,
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
