# Generated by Django 5.0.6 on 2024-06-09 07:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mailing',
            field=models.ForeignKey(help_text='рассылка', on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='mailapp.mailing', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='log_text',
            field=models.TextField(default=datetime.datetime(2024, 6, 9, 7, 4, 42, 915342, tzinfo=datetime.timezone.utc), help_text='введите текст лога', verbose_name='текст лога'),
        ),
    ]
