# Generated by Django 5.0.6 on 2024-06-12 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_alter_mail_mailing_alter_mailinglog_log_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='comment',
            field=models.TextField(default='', help_text='Введите комментарий', verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='mail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='log_text',
            field=models.TextField(default=datetime.datetime(2024, 6, 12, 8, 34, 42, 813721, tzinfo=datetime.timezone.utc), help_text='введите текст лога', verbose_name='текст лога'),
        ),
    ]
