# Generated by Django 5.0.6 on 2024-06-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_mailinglog_user_alter_mail_options_mail_name_mailing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
