# Generated by Django 5.0.6 on 2024-06-12 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0003_mail_comment_mail_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mail',
            new_name='Client',
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='log_text',
            field=models.TextField(default=datetime.datetime(2024, 6, 12, 8, 49, 21, 843722, tzinfo=datetime.timezone.utc), help_text='введите текст лога', verbose_name='текст лога'),
        ),
    ]
