# Generated by Django 5.0.6 on 2024-06-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='log_text',
            field=models.TextField(blank=True, help_text='введите текст лога', null=True, verbose_name='текст лога'),
        ),
    ]
