# Generated by Django 5.0.6 on 2024-06-12 09:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0004_rename_mail_client_alter_mailinglog_log_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите тему сообщения', max_length=150, verbose_name='тема сообщения')),
                ('body', models.TextField(help_text='Введите тело сообщения', verbose_name='тело сообщения')),
            ],
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='log_text',
            field=models.TextField(default=datetime.datetime(2024, 6, 12, 9, 20, 16, 575198, tzinfo=datetime.timezone.utc), help_text='введите текст лога', verbose_name='текст лога'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailapp.message', verbose_name='сообщение'),
        ),
    ]
