# Generated by Django 5.0.6 on 2024-06-12 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0007_alter_mailing_message_alter_mailinglog_log_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='message_in',
            field=models.TextField(blank=True, help_text='введите текст рассылки', null=True, verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='log_text',
            field=models.TextField(default=datetime.datetime(2024, 6, 12, 9, 23, 11, 903419, tzinfo=datetime.timezone.utc), help_text='введите текст лога', verbose_name='текст лога'),
        ),
    ]
