# Generated by Django 5.0.6 on 2024-06-13 10:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0009_alter_mailing_message_alter_mailinglog_log_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_send",
                    models.DateTimeField(
                        help_text="введите дату и время первой отправки рассылки",
                        verbose_name="дата и время первой отправки рассылки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default="1",
                        help_text="введите периодичность",
                        max_length=150,
                        verbose_name="периодичность (через сколько дней)",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="введите статус рассылки (ожидается (запущена) или завершена)",
                        verbose_name="статус",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="запущена ли рассылка сейчас",
                        verbose_name="активность",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="log_text",
            field=models.TextField(
                default=datetime.datetime(
                    2024, 6, 13, 10, 39, 38, 597599, tzinfo=datetime.timezone.utc
                ),
                help_text="введите текст лога",
                verbose_name="текст лога",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(
                default="текст рассылки",
                help_text="Введите тело сообщения",
                verbose_name="тело сообщения",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(
                default="рассылка",
                help_text="Введите тему сообщения",
                max_length=150,
                verbose_name="тема сообщения",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings",
                to="mailapp.mailingsettings",
                verbose_name="настройки",
            ),
        ),
    ]
