# Generated by Django 5.0.6 on 2024-06-13 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0010_mailingsettings_alter_mailinglog_log_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglog",
            name="mail_answer",
            field=models.TextField(
                default="No sending, create or change",
                help_text="введите ответ почтового сервера",
                verbose_name="ответ почтового сервера",
            ),
        ),
        migrations.AddField(
            model_name="mailinglog",
            name="status",
            field=models.BooleanField(
                default=True,
                help_text="введите статус попытки",
                verbose_name="статус попытки",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="log_text",
            field=models.TextField(
                default=datetime.datetime(
                    2024, 6, 13, 10, 49, 50, 964585, tzinfo=datetime.timezone.utc
                ),
                help_text="введите текст лога",
                verbose_name="текст лога",
            ),
        ),
    ]
