# Generated by Django 5.0.6 on 2024-06-14 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0015_alter_mailing_datetime_send_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="datetime_send",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="status",
        ),
        migrations.RemoveField(
            model_name="mailinglog",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="log_text",
            field=models.TextField(
                default=datetime.datetime(
                    2024, 6, 14, 10, 0, 2, 390408, tzinfo=datetime.timezone.utc
                ),
                help_text="введите текст лога",
                verbose_name="текст лога",
            ),
        ),
    ]
