# Generated by Django 5.0.6 on 2024-06-14 10:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0016_remove_mailing_datetime_send_remove_mailing_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message",
                to="mailapp.message",
                verbose_name="сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="mailapp.mailingsettings",
                verbose_name="настройки",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="log_text",
            field=models.TextField(
                default=datetime.datetime(
                    2024, 6, 14, 10, 5, 11, 464272, tzinfo=datetime.timezone.utc
                ),
                help_text="введите текст лога",
                verbose_name="текст лога",
            ),
        ),
    ]
