# Generated by Django 5.0.6 on 2024-06-16 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0017_alter_mailing_message_alter_mailing_settings_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="FreeUser",
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="log_text",
            field=models.TextField(
                default=datetime.datetime(
                    2024, 6, 16, 16, 17, 24, 159674, tzinfo=datetime.timezone.utc
                ),
                help_text="введите текст лога",
                verbose_name="текст лога",
            ),
        ),
    ]
