# Generated by Django 4.2.2 on 2024-06-16 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0018_rename_user_freeuser_alter_mailinglog_log_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="freeuser",
            options={
                "verbose_name": "simple пользователь",
                "verbose_name_plural": "simple пользователи",
            },
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="log_text",
            field=models.TextField(
                default=datetime.datetime(
                    2024, 6, 16, 17, 1, 46, 209669, tzinfo=datetime.timezone.utc
                ),
                help_text="введите текст лога",
                verbose_name="текст лога",
            ),
        ),
    ]
