# Generated by Django 4.2.2 on 2024-06-18 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0023_alter_mailinglog_log_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    (
                        "can_set_user_inactive",
                        "Can blocked user (bool is_active = False)",
                    ),
                    (
                        "can_turn_off_mailing",
                        "Can turn off mailing (mailing.settings.status = False",
                    ),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="log_text",
            field=models.TextField(
                default=datetime.datetime(
                    2024, 6, 18, 12, 49, 4, 77603, tzinfo=datetime.timezone.utc
                ),
                help_text="введите текст лога",
                verbose_name="текст лога",
            ),
        ),
    ]
