# Generated by Django 4.2.2 on 2024-06-18 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0025_alter_mailing_message_in_alter_mailing_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FreeUser",
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="log_text",
            field=models.TextField(
                default=datetime.datetime(
                    2024, 6, 18, 16, 14, 32, 142098, tzinfo=datetime.timezone.utc
                ),
                help_text="введите текст лога",
                verbose_name="текст лога",
            ),
        ),
    ]
